
DROP USER 'demos'@'localhost'
CREATE USER 'demos'@'localhost' IDENTIFIED WITH mysql_native_password BY 'demos';
GRANT ALL PRIVILEGES ON *.* TO 'demos'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

DROP DATABASE IF EXISTS demos;
CREATE DATABASE demos;
USE demos;


